pharo-open-documentation/awesome-pharo

README.md

I am not sure about the name of the new section. 
Any better idea @juliendelplanque ?

Add DeepTraverser

---

README.md

It adds Mocketry and StateSpecs links and new section TDD

Mocketry and StateSpecs

---

README.md

Added some libraries and sorted entries alphabetically.

Sorted entries alphabetically

---

README.md

We can discuss a better section for Units if needed.

Added Units in Miscellaneous section

---

README.md

With Python3Generator for now.
I think there is a project to generate Javascript I don't know the name.

Added code generation section

---

README.md

With a first video.
It has been a pain in the ass to find this video (which is the only concrete example of this framework I can understand so far).
So I thought adding a video section to this repository would be good.

Added video category

---

README.md

Adding projects

---

README.md

I propose a reference about CORMAS - a smalltalk lib for agent based models

add cormas referencies

---

README.md

Add Glorp, GlorpSQLite, and mention that P3 is also integrated with Glorp.

Add Glorp and related edits

---

README.md

Ducasse patch 2

---

README.md

Fixes #60.
I've placed this under a new **Tutorials** heading but I'm not sure that is accurate. Exercism is more like a series of exercises with guidance as needed. Similar to code Kata's but with the option of mentor feedback.
Let me know what you think.

Add Exercism Pharo-Smalltalk language track

---

README.md

Added PropertyEnvironment

---

README.md

Added some links in databases section

---

README.md

Added voyage

---

README.md

Added Magritte

---

README.md

Added libusb and HID

---

README.md

Added TOC section

---

README.md

Added HoneyGinger

---

README.md

added dataset section

---

README.md

- Created LaTeX section
- Added SmalltalkEnv
- Moved Citezen to this section

Added SmalltalkEnv

---

README.md

Added PharoJS references in code generation and system interaction + a short explanation why it fits there

Updated references to PharoJS

---

README.md

and a new category: Web API clients

Added discord st

---

README.md

Add PlantUMLPharoGizmo

---

README.md

Moved QA in it.
Added Rules project.

Created Code quality section

---

README.md

See individual commits for more details

A pass on awesome-pharo

---

README.md

Added Arff entry.

---

README.md

Added dawn theme.

---

README.md

Added Uncommon-Themes

---

README.md

Added Mathemagics package and fix a typo in another line.

Added Mathemagics package

---

README.md

Update to Roassal to 3

---

README.md

add visitorGenerator

---

README.md

Add my IOT project on the Legrand/Netatmo products API

Add my IOT project on the Legrand/Netatmo products API

---

README.md

Added ReStore to DB section

---

README.md

Added Webside IDE link

---

README.md

Issue: https://github.com/pharo-open-documentation/awesome-pharo/issues/93

Add WebSocket

---

README.md

Added link to WebST + Update link to PharoJS
